### ISSUE TITLE
Plugin not working as intended

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/PlaynitePlugin-SteamStoreMetadata#15]
I want horizontal covers for my games, so I set it to the Steam horizontal ratio.

![2022-01-04 20_39_23-Window](https://user-images.githubusercontent.com/16439116/148115475-2a020c39-45dd-4f33-a0bf-de681664bac0.png)

When I do a manual metadata download of just the cover (of RAD from my Amazon Games library)from the Steam store...

![2022-01-04 20_31_00-Window](https://user-images.githubusercontent.com/16439116/148116267-d419d8b4-76cd-4f6f-84ec-613a9b1e586f.png)

... I get the same result. A vertical cover

![2022-01-04 20_31_38-Window](https://user-images.githubusercontent.com/16439116/148116480-528ee5a2-f7ec-470f-a34c-faeb83d369ed.png)

Automatic and manual metadata downloads yield the same results.

Steam has the horizontal cover

![2022-01-04 20_34_00-Window](https://user-images.githubusercontent.com/16439116/148116567-0d6caa2d-769a-4ef7-9f76-8492a640f2d3.png)

A manual Google search also returns the correct cover.

![2022-01-04 20_33_25-Window](https://user-images.githubusercontent.com/16439116/148116674-68700d2b-cf15-4a47-a3e9-e09a23fb738f.png)

Is the plugin not working as intended or am I missing something?

**Comment by JosefNemec** [comment]
You need to change it in extension's settings. There's an option to choose vertical or horizontal covers.
