### ISSUE TITLE
"doesn't support current version of Playnite SDK / dependencices are not compatible"

### ISSUE THREAD

**Issue by bverkron** [JosefNemec/PlaynitePlugin-SteamStoreMetadata#16]
Tried to install and use this plugin today and it fails to load. Maybe this plugin no longer works with Playnite v9+?

![image](https://user-images.githubusercontent.com/19174503/149709319-0332a121-44b1-4cc9-8fe4-773bfa8c90a5.png)

> 16-01 20:36:49.771|ERROR|ExtensionFactory:Plugin doesn't support current version of Playnite SDK, supports 5.2.0.0
> 16-01 20:36:49.771|ERROR|ExtensionFactory:Plugin dependencices are not compatible: Universal Steam Metadata

I primarily wanted to use this plugin to get more specific split screen metadata. For example most games only state "Split Screen" very broadly but I have saved filters that show games that are "Shared/Split Screen PvP" vs Shared/Split Screen Co-op", etc depending on what me and my kids / friends are in the mood for. IGDB and Official Store rarely seem to get that granular, was hoping this plugin would solve that.

**Comment by JosefNemec** [comment]
You need to install version of this plugin from add-on browser. This repository is obsolete.
