### ISSUE TITLE
Metadata in languages other than English

### ISSUE THREAD

**Issue by Greentaily** [JosefNemec/PlaynitePlugin-SteamStoreMetadata#4]
This is currently unsupported but it seems that a few lines of code would be sufficient. I figured that the language in which https://store.steampowered.com/ is served depends on the "Steam_Language" cookie which is by default set to "english".

I don't have any meaningful experience with C#, however, I went through the code of the extension and the way it is implemented seems that it simply downloads webpages via URL using WebClient thing. It seems possible to include a cookie with a one-liner (https://stackoverflow.com/questions/13275042/add-cookie-to-webclient). It seems that other than that, only a drop-down menu in the extension settings would be needed. 

The list of languages supported by Steam and their respective codes are available [here](https://partner.steamgames.com/doc/store/localization).

This feature would be neat as default metadata providers in Playnite do not support languages other than English. I'm good enough at English but my family and friends know none of it, and I have a gaming rig connected to a TV set attached to a wall for couch coop sessions that runs Playnite in fullscreen mode on system startup. I'm pretty sure my use case is not unique. I could try and make a fork of the code and see whether what I suggest works (though I have very limited experience with git as well).

**Comment by JosefNemec** [comment]
I don't plan adding support for other languages for one main reason, not all data would be localized. Most of the other stores and IGDB don't have localized data. So you would end up with weird mashup of localized and non-localized fields, which would also cause duplicates.

**Comment by Greentaily** [comment]
Sad! As I understand it though, It's possible to only use data provided by Steam which would be localized entirely and in many cases should be enough.

I'll try and modify the code and see what happens, the process seems interesting anyway.

**Comment by Greentaily** [comment]
Sadly I didn't. You can try too though. :smile:

**Comment by nibau** [comment]
I recently ran into this issue.

If you want the metadata in a different language, all you need to do is change the url parameter [here](https://github.com/JosefNemec/PlaynitePlugin-SteamStoreMetadata/blob/1cc69aaeea800c4664227a1d37763fbd4cb2bda5/source/UniversalSteamMetadata/SteamShared/WebApiClient.cs#L23) from "english" to your desired language (e.g. "german" for German).

With this it will generally download all metadata in your selected language (including localized feature names like "Einzelspieler" instead of "Single Player"). If metadata is not available in the selected language, Steam automatically falls back to provinding English metadata.

**Comment by DeN-AlB** [comment]
>If you want the metadata in a different language, all you need to do is change the url parameter here from "english" to your desired language (e.g. "german" for German).
Sounds good. I will try if it works. Thanks! :)

**Comment by DeN-AlB** [comment]
@nibau 
How do I edit this file? It is not in the extension folder.
I just opened your link and saved this modified file into a folder called "SteamShared" of the extension. But still the description is loaded in English.

**Comment by JosefNemec** [comment]
My stance on this is still relevant and I don't want to provide this feature unless we can provide all data for all supported libraries in specified language (which is not possible):

https://github.com/JosefNemec/Playnite/issues/136#issuecomment-633020489
https://github.com/JosefNemec/PlaynitePlugin-SteamStoreMetadata/issues/4#issuecomment-633019722

Therefore I'm going to close this.

You can create custom metadata plugin for providing localized descriptions or use [existing plugin by Larco59](https://playnite.link/forum/thread-291.html).
