### ISSUE TITLE
Metadata download fails in cases where gamename is different for Steam store game name

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/PlaynitePlugin-SteamStoreMetadata#5]
Seems to happen with games that have special symbols and characters so they should be ignored/removed for better matching and ideally only letters and numbers should be used. For example:

Game name = `Sid Meier's Civilization VI`
Steam Store game name: = `Sid Meier's Civilization® VI`

**Comment by JosefNemec** [comment]
Done in 1.3
