### ISSUE TITLE
Search by App ID

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/PlaynitePlugin-SteamStoreMetadata#7]
In addition to search by name, it can be able to search by App ID in the window with search result selection.

**Comment by JosefNemec** [comment]
Done in 1.3

**Comment by OsoaGitHub** [comment]
@JosefNemec sorry if this is a stupid question but how do you do this?

**Comment by JosefNemec** [comment]
Put game ID into search box.
![image](https://user-images.githubusercontent.com/3874087/132891080-f8ab5a06-fbf2-4d23-ac51-3ed6b52959eb.png)

**Comment by OsoaGitHub** [comment]
I don't see a search box... it just goes straight to the background image selection...

> 
> 
> Put game ID into search box.
> ![image](https://user-images.githubusercontent.com/3874087/132891080-f8ab5a06-fbf2-4d23-ac51-3ed6b52959eb.png)

**Comment by JosefNemec** [comment]
If you are using it on a Steam game then it won't give you search option because it knows what Steam game data to use.

**Comment by OsoaGitHub** [comment]
> 
> 
> If you are using it on a Steam game then it won't give you search option because it knows what Steam game data to use.

could you add support for this? I want to scrape data for Skyrim (original) instead of Skyrim Special Edition
